const data = {
  products: [
    {
      _id: '1',
      name: 'Samsung Galaxy S22 Ultra',
      slug: 'Samsung',
      category: 'Mobile',
      image: '/images/p1.jpg',
      price: 1200,
      countInStock: 10,
      brand: 'Samsung',
      rating: 5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      _id: '2',
      name: 'Iphone 13 ProMax',
      slug: 'Iphone',
      category: 'Mobile',
      image: '/images/p2.jpg',
      price: 1200,
      countInStock: 12,
      brand: 'Apple',
      rating: 5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      _id: '3',
      name: 'Redmi Note 20',
      slug: 'Redmi Note',
      category: 'Mobile',
      image: '/images/p3.jpg',
      price: 1200,
      countInStock: 15,
      brand: 'Redmi',
      rating: 5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      _id: '4',
      name: 'Mac Book Pro',
      slug: 'Mac Laptop',
      category: 'Laptop',
      image: '/images/p4.png',
      price: 1200,
      countInstock: 5,
      brand: 'Apple',
      rating: 5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      _id: '5',
      name: 'Nvidia Graphic RTX 3090',
      slug: 'Nvidia Graphics',
      category: 'Eletronic',
      image: '/images/p5.png',
      price: 1200,
      countInStock: 0,
      brand: 'Nvidia',
      rating: 5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      _id: '6',
      name: 'Nvidia Graphic GTX 970',
      slug: 'Nvidia Graphics GTX',
      category: 'Eletronic',
      image: '/images/p6.jpg',
      price: 560,
      countInStock: 27,
      brand: 'Nvidia',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
  ],
};

export default data;
